//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Safe {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Safe.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accesibility.
        /// </summary>
        internal static string accesibility {
            get {
                return ResourceManager.GetString("accesibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accesibility Mode.
        /// </summary>
        internal static string accesibility_mode {
            get {
                return ResourceManager.GetString("accesibility_mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alert.
        /// </summary>
        internal static string alert {
            get {
                return ResourceManager.GetString("alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you okay?.
        /// </summary>
        internal static string alert_question {
            get {
                return ResourceManager.GetString("alert_question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CLICK!.
        /// </summary>
        internal static string click_fast {
            get {
                return ResourceManager.GetString("click_fast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contact message.
        /// </summary>
        internal static string contact_message {
            get {
                return ResourceManager.GetString("contact_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contact number.
        /// </summary>
        internal static string contact_number {
            get {
                return ResourceManager.GetString("contact_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Manage car accidents.
        /// </summary>
        internal static string crash_status {
            get {
                return ResourceManager.GetString("crash_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Activity.
        /// </summary>
        internal static string danger_activity {
            get {
                return ResourceManager.GetString("danger_activity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Default message.
        /// </summary>
        internal static string default_message {
            get {
                return ResourceManager.GetString("default_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Safe App, Italy, 2017.
        /// </summary>
        internal static string develop_info {
            get {
                return ResourceManager.GetString("develop_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Emergency Number.
        /// </summary>
        internal static string emergency_number {
            get {
                return ResourceManager.GetString("emergency_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Manage fallings.
        /// </summary>
        internal static string falls_status {
            get {
                return ResourceManager.GetString("falls_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hardware config.
        /// </summary>
        internal static string hardware_config {
            get {
                return ResourceManager.GetString("hardware_config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hardware.
        /// </summary>
        internal static string hardware_page_tittle {
            get {
                return ResourceManager.GetString("hardware_page_tittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a info.
        /// </summary>
        internal static string info {
            get {
                return ResourceManager.GetString("info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Language .
        /// </summary>
        internal static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No.
        /// </summary>
        internal static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pasword configuration.
        /// </summary>
        internal static string password_config {
            get {
                return ResourceManager.GetString("password_config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Personal Info configuration.
        /// </summary>
        internal static string personal_info_config {
            get {
                return ResourceManager.GetString("personal_info_config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pin code.
        /// </summary>
        internal static string pin_code {
            get {
                return ResourceManager.GetString("pin_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SAVE.
        /// </summary>
        internal static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save settings.
        /// </summary>
        internal static string save_settings {
            get {
                return ResourceManager.GetString("save_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Do you want notify to your contact?.
        /// </summary>
        internal static string send_message {
            get {
                return ResourceManager.GetString("send_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Settings.
        /// </summary>
        internal static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Display Map.
        /// </summary>
        internal static string show_map {
            get {
                return ResourceManager.GetString("show_map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a tap twice for stop.
        /// </summary>
        internal static string stop_message {
            get {
                return ResourceManager.GetString("stop_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a tap twice to start.
        /// </summary>
        internal static string tap_start {
            get {
                return ResourceManager.GetString("tap_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a tap twice.
        /// </summary>
        internal static string tap_twice {
            get {
                return ResourceManager.GetString("tap_twice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Display test page.
        /// </summary>
        internal static string test_page {
            get {
                return ResourceManager.GetString("test_page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Testing.
        /// </summary>
        internal static string testing {
            get {
                return ResourceManager.GetString("testing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Use pin.
        /// </summary>
        internal static string use_pin {
            get {
                return ResourceManager.GetString("use_pin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vibration Status.
        /// </summary>
        internal static string vibration_status {
            get {
                return ResourceManager.GetString("vibration_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Warning.
        /// </summary>
        internal static string warning {
            get {
                return ResourceManager.GetString("warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Yes.
        /// </summary>
        internal static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
    }
}
